baseURL = "https://tdg-pod.netlify.app/"
languageCode = "en-gb"
title = "The Daily GOings"
theme = "hyde"

[markup]
    defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
  hardWraps = true

[params]
  themeColor = "theme-base-06"
  layoutReverse = true
  description = "A daily podcast about Pokémon GO"
  author = "Hannah"
  email = "todo@todo"
  category = "Leisure"
  subcategory = "Video Games"
  year = "2023"
  itunes = "todo"
  pocketcasts = "todo"
  overcast = "todo"
  spotify = "todo"

[menu]

  [[menu.main]]
    identifier = "patreon"
    name = "Patreon"
    title = "patreon"
    url = "todo"
    weight = -1